# Generated by Django 6.1 on 2026-09-02 02:50

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Papel',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(choices=[('GESTOR', 'Gestor de Projetos'), ('TESTER', 'Tester'), ('DEV', 'Desenvolvedor')], max_length=20, unique=True)),
                ('nome_exibicao', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name_plural': 'papéis',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True, default='')),
                ('modo', models.CharField(choices=[('UAT', 'UAT'), ('CUTOVER', 'Cutover')], max_length=10)),
                ('nivel1_nome', models.CharField(max_length=60)),
                ('nivel2_nome', models.CharField(blank=True, max_length=60, null=True)),
                ('aging_alerta_dias', models.IntegerField(default=2)),
                ('aging_risco_dias', models.IntegerField(default=6)),
                ('spi_saudavel', models.DecimalField(decimal_places=2, default=Decimal('0.90'), max_digits=3)),
                ('spi_critico', models.DecimalField(decimal_places=2, default=Decimal('0.75'), max_digits=3)),
                ('anexo_max_mb', models.IntegerField(default=10)),
                ('exigir_evidencia_atividade', models.BooleanField(default=True)),
                ('exigir_evidencia_issue', models.BooleanField(default=True)),
                ('proximo_codigo_atividade', models.IntegerField(default=1)),
                ('proximo_codigo_issue', models.IntegerField(default=1)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projetos_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-atualizado_em', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='NoHierarquia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nivel', models.PositiveSmallIntegerField(choices=[(1, 'Nível 1'), (2, 'Nível 2')])),
                ('nome', models.CharField(max_length=100)),
                ('ordem', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filhos', to='projects.nohierarquia')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nos_hierarquia', to='projects.project')),
            ],
            options={
                'verbose_name': 'nó de hierarquia',
                'verbose_name_plural': 'nós de hierarquia',
                'ordering': ['projeto', 'nivel', 'ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('convidado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='convites_projeto', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros_projeto', to=settings.AUTH_USER_MODEL)),
                ('papel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='projects.papel')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='projects.project')),
            ],
            options={
                'ordering': ['projeto', 'usuario', 'papel'],
            },
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(('modo', 'UAT'), ('modo', 'CUTOVER'), _connector='OR'), name='project_modo_valido'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('modo', 'UAT'), ('nivel2_nome__isnull', False)), models.Q(('modo', 'CUTOVER'), ('nivel2_nome__isnull', True)), _connector='OR'), name='project_niveis_por_modo'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(('aging_alerta_dias__gte', 0)), name='project_aging_alerta_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(('aging_risco_dias__gte', 0)), name='project_aging_risco_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(('anexo_max_mb__gt', 0)), name='project_anexo_max_mb_positivo'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(('proximo_codigo_atividade__gt', 0)), name='project_proximo_codigo_atividade_positivo'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(('proximo_codigo_issue__gt', 0)), name='project_proximo_codigo_issue_positivo'),
        ),
        migrations.AddConstraint(
            model_name='nohierarquia',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('nivel', 1), ('parent__isnull', True)), models.Q(('nivel', 2), ('parent__isnull', False)), _connector='OR'), name='no_hierarquia_parent_por_nivel'),
        ),
        migrations.AddConstraint(
            model_name='nohierarquia',
            constraint=models.UniqueConstraint(fields=('projeto', 'parent', 'nome'), name='no_hierarquia_nome_unico_por_parent', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('usuario', 'projeto', 'papel'), name='membership_usuario_projeto_papel_unico'),
        ),
    ]
