# Generated by Django 6.1 on 2026-09-03 23:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_seed_papeis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-criado_em', 'nome']},
        ),
        migrations.AddField(
            model_name='project',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(condition=models.Q(('ativo', True)), fields=('nome', 'modo'), name='project_nome_modo_ativo_unico'),
        ),
    ]
