# Generated by Django 6.1 on 2026-09-09 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_options_project_ativo_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='project',
            name='project_proximo_codigo_atividade_positivo',
        ),
        migrations.RemoveField(
            model_name='project',
            name='proximo_codigo_atividade',
        ),
    ]
