# Generated by Django 6.1 on 2026-09-12 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0002_remove_em_execucao_status'),
        ('projects', '0004_remove_project_project_proximo_codigo_atividade_positivo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('EM_ANALISE', 'Em análise'), ('SOLUCAO_PROPOSTA', 'Solução proposta'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='ABERTA', max_length=20)),
                ('impeditiva', models.BooleanField(default=False)),
                ('tipo', models.CharField(choices=[('REQUISITO', 'Requisito'), ('PERFORMANCE', 'Performance'), ('DADOS', 'Dados'), ('INTEGRACAO', 'Integração'), ('INTERFACE', 'Interface'), ('CONFIGURACAO', 'Configuração'), ('OUTRO', 'Outro')], max_length=20)),
                ('impacto', models.CharField(choices=[('MUITO_ALTO', 'Muito alto'), ('ALTO', 'Alto'), ('MEDIO', 'Médio'), ('BAIXO', 'Baixo')], max_length=20)),
                ('nota_impacto', models.CharField(blank=True, default='', max_length=255)),
                ('solucao_proposta', models.TextField(blank=True, default='')),
                ('anexo_abertura', models.JSONField(blank=True, null=True)),
                ('anexo_solucao', models.JSONField(blank=True, null=True)),
                ('analise_iniciada_em', models.DateTimeField(blank=True, null=True)),
                ('solucao_proposta_em', models.DateTimeField(blank=True, null=True)),
                ('resolvida_em', models.DateTimeField(blank=True, null=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='activities.activity')),
                ('desenvolvedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues_como_desenvolvedor', to=settings.AUTH_USER_MODEL)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='projects.project')),
                ('tester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues_como_tester', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'issue',
                'verbose_name_plural': 'issues',
                'ordering': ['-criada_em', '-id'],
            },
        ),
    ]
