# Generated by Django 6.1 on 2026-09-09 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_alter_project_options_project_ativo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('AGUARDANDO', 'Aguardando'), ('LIBERADO', 'Liberado'), ('EM_EXECUCAO', 'Em execução'), ('BLOQUEADO', 'Bloqueado'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='LIBERADO', max_length=20)),
                ('data_inicio_planejada', models.DateField()),
                ('data_conclusao_planejada', models.DateField()),
                ('data_inicio_real', models.DateField(blank=True, null=True)),
                ('data_conclusao_real', models.DateField(blank=True, null=True)),
                ('numero_retest', models.IntegerField(default=0)),
                ('area', models.CharField(blank=True, default='', max_length=100)),
                ('sistema', models.CharField(blank=True, default='', max_length=100)),
                ('transacao', models.CharField(blank=True, default='', max_length=50)),
                ('wbs', models.CharField(blank=True, default='', max_length=50)),
                ('resultado_esperado', models.TextField(blank=True, default='')),
                ('observacoes', models.TextField(blank=True, default='')),
                ('observacao_aprovacao', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('desenvolvedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities_como_desenvolvedor', to=settings.AUTH_USER_MODEL)),
                ('no', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='projects.nohierarquia')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='projects.project')),
                ('tester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities_como_tester', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'atividade',
                'verbose_name_plural': 'atividades',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ActivityPredecessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predecessor_edges', to='activities.activity')),
                ('predecessora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependent_edges', to='activities.activity')),
            ],
            options={
                'verbose_name': 'predecessora de atividade',
                'verbose_name_plural': 'predecessoras de atividades',
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='predecessoras',
            field=models.ManyToManyField(blank=True, related_name='dependentes', through='activities.ActivityPredecessor', through_fields=('atividade', 'predecessora'), to='activities.activity'),
        ),
        migrations.AddConstraint(
            model_name='activitypredecessor',
            constraint=models.UniqueConstraint(fields=('atividade', 'predecessora'), name='activity_predecessor_unica'),
        ),
        migrations.AddConstraint(
            model_name='activitypredecessor',
            constraint=models.CheckConstraint(condition=models.Q(('atividade', models.F('predecessora')), _negated=True), name='activity_predecessor_nao_self'),
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.CheckConstraint(condition=models.Q(('data_inicio_planejada__lte', models.F('data_conclusao_planejada'))), name='activity_datas_planejadas_ordem'),
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.CheckConstraint(condition=models.Q(('numero_retest__gte', 0)), name='activity_numero_retest_nao_negativo'),
        ),
    ]
