# Generated by Codex on 2026-09-10

from django.db import migrations, models


def migrar_em_execucao_para_liberado(apps, schema_editor):
    Activity = apps.get_model("activities", "Activity")
    Activity.objects.filter(status="EM_EXECUCAO").update(status="LIBERADO")


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(migrar_em_execucao_para_liberado, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="activity",
            name="status",
            field=models.CharField(
                choices=[
                    ("AGUARDANDO", "Aguardando"),
                    ("LIBERADO", "Liberado"),
                    ("BLOQUEADO", "Bloqueado"),
                    ("CONCLUIDO", "Concluído"),
                    ("CANCELADO", "Cancelado"),
                ],
                default="LIBERADO",
                max_length=20,
            ),
        ),
    ]
